### ISSUE TITLE
total_hba_conflicts always empty

### ISSUE THREAD

**Issue by did16** [RafiaSabih/pg_auth_mon#10]
Hi
I have configured pg_auth_mon in a 13 PostgreSQL cluster. I perform configuration tests of the pg_hba.conf file. I have error messages on the screen but in the pg_auth_mon view, " total_hba_conflicts " is always empty.
Is there a problem, a bug with this functionality ?

Thanks in advance
Didier

**Comment by RafiaSabih** [comment]
Hello Didier,

Unfortunately, as per postgres design, in case of hba conflict errors, it
never reaches hook and hence the empty field.

With regards,
-Rafia
