### ISSUE TITLE
Regression tests are failing

### ISSUE THREAD

**Issue by devrimgunduz** [RafiaSabih/pg_auth_mon#17]
Hi @RafiaSabih ,

Regression tests are failing against at least v15 and v16. Diff is attached. Can you please take a look?

Regards, Devrim

[regression.diffs.txt](https://github.com/RafiaSabih/pg_auth_mon/files/12550283/regression.diffs.txt)

**Comment by devrimgunduz** [comment]
ping

**Comment by RafiaSabih** [comment]
Resolved with latest commit.
