### ISSUE TITLE
Build error against PostgreSQL 17

### ISSUE THREAD

**Issue by devrimgunduz** [RafiaSabih/pg_auth_mon#19]
Hi,

Latest release fails to build against PostgreSQL 17.  v17beta2 is already out. Logs are below. Can you please take a look?

Thanks, Devrim

> /usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-format-truncation -O2  -I. -I./ -I/usr/pgsql-17/include/server -I/usr/pgsql-17/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2 -DWITH_GZFILEOP  -I/usr/include -flto=thin -emit-llvm -c -o pg_auth_mon.bc pg_auth_mon.c
pg_auth_mon.c:523:2: error: call to undeclared function 'tuplestore_donestoring'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  523 |         tuplestore_donestoring(tupstore);
      |         ^
1 error generated.
make[1]: *** [/usr/pgsql-17/lib/pgxs/src/makefiles/../../src/Makefile.global:1085: pg_auth_mon.bc] Error 1
make[1]: *** Waiting for unfinished jobs....
pg_auth_mon.c: In function ‘pg_auth_mon_internal’:
pg_auth_mon.c:523:9: error: implicit declaration of function ‘tuplestore_donestoring’; did you mean ‘tuplestore_rescan’? [-Wimplicit-function-declaration]
  523 |         tuplestore_donestoring(tupstore);
      |         ^~~~~~~~~~~~~~~~~~~~~~
      |         tuplestore_rescan
make[1]: *** [<builtin>: pg_auth_mon.o] Error 1

**Comment by devrimgunduz** [comment]
Hi,

Attached patch fixes the error:

[pg_auth_mon-pg17.patch.txt](https://github.com/user-attachments/files/16428815/pg_auth_mon-pg17.patch.txt)

**Comment by RafiaSabih** [comment]
Hello Devrim,

Thanks for pointing this out. I will take care of it this week. Sorry for
the delay.

**Comment by RafiaSabih** [comment]
Fixed [here](https://github.com/RafiaSabih/pg_auth_mon/pull/20).

**Comment by devrimgunduz** [comment]
Hi @RafiaSabih ,

Thanks! Can you please a new version so that I can build RPMs?

Regards, Devrim

**Comment by RafiaSabih** [comment]
[There](https://github.com/RafiaSabih/pg_auth_mon/releases/tag/v3.0) you go.
