### ISSUE TITLE
can this extension ban user login when they exceed max fail login attempts?

### ISSUE THREAD

**Issue by yanghuantian** [RafiaSabih/pg_auth_mon#6]
hi:
  I find there is no way to ban the user from login,because in authentication_hook , i can't use spi_exec to run command like(alter user xx nologin), is there anyway to ban a user from login in authentication_hook when it exceeds the max fail login times?

**Comment by RafiaSabih** [comment]
Hi,

Thanks for your interest in the extension. You are right, there is no way to ban or lock out any user. The intention of this extension is just to log the access attempts. Feel free to extend it in the directions you require.

**Comment by yanghuantian** [comment]
> Hi,
> 
> Thanks for your interest in the extension. You are right, there is no way to ban or lock out any user. The intention of this extension is just to log the access attempts. Feel free to extend it in the directions you require.

Thank you for your prompt reply，my English is not so good， actually i want  to know if there is a way to ban a user from logging in the hook function？like a api change a user's privil or other.. because i find the status is passed to the authentication_hook function by value not by reference, i can't do it by change the status.
     Do you have any good suggestions？ thank you very much
