### ISSUE TITLE
How to install ph_auth_mon

### ISSUE THREAD

**Issue by did16** [RafiaSabih/pg_auth_mon#7]
Hi
I failed to install the pg_auth_mon extension. Is there detailed documentation that explains how to do this?
is it possible to have support on the installation of the product?

Thanks in advance

Best Regards

**Comment by RafiaSabih** [comment]
Currently, you may install it like any other postgres extension,
- clone the repo in  postgres contrib folder
- run make and make install
- use create extension pg_auth_mon at the client

Feel free to point out any issues you encounter. Will add documentation on how to install it, etc. or if you'd like, add a PR for the same.

**Comment by did16** [comment]
Hi
thank you for the answer.
I would like the extension pg_auth_mon to be included in the postgresql community packages list maintened by Devrim Gunduz. He agrees but to do that, you need to create releases for this extension. Can you do that in github?

**Comment by did16** [comment]
Hi Rafia
Devrim Gündüz  need a tarball to build a package rpm in the postgresql community packages list. Do you think it is possible to do that ?

**Comment by RafiaSabih** [comment]
That's good to know. Certainly, I can do that, here it [is](https://github.com/RafiaSabih/pg_auth_mon/releases), hope it helps you.

**Comment by did16** [comment]
Hi Rabia
THank you very much for this first release. 
I contacted Devrim Gündüz to put the extension in the rpm packages PGDG repository.

**Comment by did16** [comment]
Hi
I try to install the new release in my environment and i get the error message : 
[postgres@DCEYY1YF pg_auth_mon-1.0]$ make
Makefile:16: /usr/pgsql-11/lib/pgxs/src/makefiles/pgxs.mk: No such file or directory
make: *** No rule to make target `/usr/pgsql-11/lib/pgxs/src/makefiles/pgxs.mk'.  Stop.

**Comment by RafiaSabih** [comment]
Please ensure correct PG_CONFIG is set and in path.

**Comment by did16** [comment]
Hi
Here is my pg_config  : 
[postgres@DCEYY1YF pg_auth_mon-1.0]$ /usr/pgsql-11/bin/pg_config
BINDIR = /usr/pgsql-11/bin
DOCDIR = /usr/pgsql-11/doc
HTMLDIR = /usr/pgsql-11/doc/html
INCLUDEDIR = /usr/pgsql-11/include
PKGINCLUDEDIR = /usr/pgsql-11/include
INCLUDEDIR-SERVER = /usr/pgsql-11/include/server
LIBDIR = /usr/pgsql-11/lib
PKGLIBDIR = /usr/pgsql-11/lib
LOCALEDIR = /usr/pgsql-11/share/locale
MANDIR = /usr/pgsql-11/share/man
SHAREDIR = /usr/pgsql-11/share
SYSCONFDIR = /etc/sysconfig/pgsql
PGXS = /usr/pgsql-11/lib/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--enable-rpath' '--prefix=/usr/pgsql-11' '--includedir=/usr/pgsql-11/include' '--libdir=/usr/pgsql-11/lib' '--mandir=/usr/pgsql-11/share/man' '--datadir=/usr/pgsql-11/share' '--with-icu' '--with-llvm' '--with-perl' '--with-python' '--with-tcl' '--with-tclconfig=/usr/lib64' '--with-openssl' '--with-pam' '--with-gssapi' '--with-includes=/usr/include' '--with-libraries=/usr/lib64' '--enable-nls' '--enable-dtrace' '--with-uuid=e2fs' '--with-libxml' '--with-libxslt' '--with-ldap' '--with-selinux' '--with-systemd' '--with-system-tzdata=/usr/share/zoneinfo' '--sysconfdir=/etc/sysconfig/pgsql' '--docdir=/usr/pgsql-11/doc' '--htmldir=/usr/pgsql-11/doc/html' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' 'LDFLAGS=-Wl,--as-needed' 'LLVM_CONFIG=/usr/lib64/llvm5.0/bin/llvm-config' 'CLANG=/opt/rh/llvm-toolset-7/root/usr/bin/clang' 'PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -L/usr/lib64/llvm5.0/lib -L/usr/lib64 -Wl,--as-needed -Wl,-rpath,'/usr/pgsql-11/lib',--enable-new-dtags
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lpthread -lselinux -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -lreadline -lrt -lcrypt -ldl -lm
VERSION = PostgreSQL 11.10

Here is my $PATH : 
[postgres@DCEYY1YF ~]$ echo $PATH
/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/postgres/.local/bin:/home/postgres/bin:/usr/pgsql-11/bin/:/usr/pgsql-11/bin/pg_config

and then the result of make : 
[postgres@DCEYY1YF pg_auth_mon-1.0]$ make
/usr/pgsql-11/lib/pgxs/src/makefiles/pgxs.mk:82: /usr/pgsql-11/lib/pgxs/src/makefiles/../../src/Makefile.global: No such file or directory
/usr/pgsql-11/lib/pgxs/src/makefiles/pgxs.mk:221: /src/Makefile.shlib: No such file or directory
make: *** No rule to make target `/src/Makefile.shlib'.  Stop.

**Comment by RafiaSabih** [comment]
Have you already done,
```
sudo apt-get install postgresql-server-dev-all
sudo apt-get install postgresql-common
```

**Comment by did16** [comment]
Hi Rafia
Does the extension pg_auth_mon only works on DEBIAN LINUX ?. I use now Linux RHEL.

**Comment by RafiaSabih** [comment]
There is nothing inherently in the extension which should restrict it based on OS flavors. However, I have not tried it myself on different platforms.
