### ISSUE TITLE
test pg_auth_mon fails on PostgreSQL 13.2

### ISSUE THREAD

**Issue by joelonsql** [RafiaSabih/pg_auth_mon#9]
Hi Rafia,

Thanks for making pg_auth_mon.

It looks like there is a problem with the tests probably due to changes in PostgreSQL's error messages:

    $ lsb_release -a
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 20.04.2 LTS
    Release:	20.04
    Codename:	focal

    $ psql --version
    psql (PostgreSQL) 13.2 (Ubuntu 13.2-1.pgdg20.04+1)

    $ make installcheck
    /usr/lib/postgresql/13/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/usr/lib/postgresql/13/bin'    --dbname=contrib_regression pg_auth_mon
    (using postmaster on Unix socket, default port)
    ============== dropping database "contrib_regression" ==============
    DROP DATABASE
    ============== creating database "contrib_regression" ==============
    CREATE DATABASE
    ALTER DATABASE
    ============== running regression test queries        ==============
    test pg_auth_mon                  ... FAILED      364 ms

    ======================
    1 of 1 tests failed.
    ======================

    The differences that caused some tests to fail can be viewed in the
    file "/home/joel/postgresql-extensions/pg_auth_mon/regression.diffs".  A copy of the test summary that you see
    above is saved in the file "/home/joel/postgresql-extensions/pg_auth_mon/regression.out".

    make: *** [/usr/lib/postgresql/13/lib/pgxs/src/makefiles/pgxs.mk:420: installcheck] Error 1

    $ cat regression.diffs
    diff -U3 /home/joel/postgresql-extensions/pg_auth_mon/expected/pg_auth_mon.out /home/joel/postgresql-extensions/pg_auth_mon/results/pg_auth_mon.out
    --- /home/joel/postgresql-extensions/pg_auth_mon/expected/pg_auth_mon.out	2021-04-26 07:11:33.097400173 +0000
    +++ /home/joel/postgresql-extensions/pg_auth_mon/results/pg_auth_mon.out	2021-04-26 07:13:21.827350943 +0000
    @@ -5,47 +5,24 @@
    create extension pg_auth_mon;
    --1.Successful Login attempt
    \! PGPASSWORD=postgres psql -X -U auth_super -d testdb -c "select 1"
    - ?column?
    -----------
    -        1
    -(1 row)
    -
    +psql: error: FATAL:  Peer authentication failed for user "auth_super"
    select rolname, successful_attempts, total_hba_conflicts, other_auth_failures from pg_auth_mon where rolname like 'auth_%';
    -  rolname   | successful_attempts | total_hba_conflicts | other_auth_failures
    -------------+---------------------+---------------------+---------------------
    - auth_super |                   1 |                   0 |                   0
    -(1 row)
    -
    +ERROR:  pg_auth_mon must be loaded via shared_preload_libraries
    --2.Login attempt by invalid username
    \! PGPASSWORD=postgres psql -X -U auth_blah -d testdb  -c "select 1" 2>&1 | sed 's/^.* FATAL: */FATAL: /'
    -FATAL: password authentication failed for user "auth_blah"
    +FATAL: Peer authentication failed for user "auth_blah"
    select rolname, uid, successful_attempts, total_hba_conflicts, other_auth_failures from pg_auth_mon where uid = 0;
    - rolname | uid | successful_attempts | total_hba_conflicts | other_auth_failures
    ----------+-----+---------------------+---------------------+---------------------
    -         |   0 |                   0 |                   0 |                   1
    -(1 row)
    -
    +ERROR:  pg_auth_mon must be loaded via shared_preload_libraries
    --3.Login attempt by username who is not allowed to login is not authentication failure
    \! PGPASSWORD=postgres psql -X -U auth_nologin -d testdb -c "select 1" 2>&1 | sed 's/^.* FATAL: */FATAL: /'
    -FATAL: role "auth_nologin" is not permitted to log in
    +FATAL: Peer authentication failed for user "auth_nologin"
    select rolname, successful_attempts, total_hba_conflicts, other_auth_failures from pg_auth_mon where rolname like 'auth_%';
    -   rolname    | successful_attempts | total_hba_conflicts | other_auth_failures
    ---------------+---------------------+---------------------+---------------------
    - auth_nologin |                   1 |                   0 |                   0
    - auth_super   |                   1 |                   0 |                   0
    -(2 rows)
    -
    +ERROR:  pg_auth_mon must be loaded via shared_preload_libraries
    --4.Login attempt by a valid user with a wrong password
    \! PGPASSWORD=postgres psql -X -U auth_test -d testdb -c "select 1" 2>&1 | sed 's/^.* FATAL: */FATAL: /'
    -FATAL: password authentication failed for user "auth_test"
    +FATAL: Peer authentication failed for user "auth_test"
    select rolname, successful_attempts, total_hba_conflicts, other_auth_failures from pg_auth_mon where rolname like 'auth_%' order by rolname;
    -   rolname    | successful_attempts | total_hba_conflicts | other_auth_failures
    ---------------+---------------------+---------------------+---------------------
    - auth_nologin |                   1 |                   0 |                   0
    - auth_super   |                   1 |                   0 |                   0
    - auth_test    |                   0 |                   0 |                   1
    -(3 rows)
    -
    +ERROR:  pg_auth_mon must be loaded via shared_preload_libraries
    --Cleanup
    drop role auth_nologin;
    drop role auth_test;

**Comment by devrimgunduz-edb** [comment]
Same with PostgreSQL 12. So I believe it was broken all the way:


[regression.diffs.log](https://github.com/RafiaSabih/pg_auth_mon/files/6549974/regression.diffs.log)

**Comment by RafiaSabih** [comment]
It is mentioned in README file that if the test is run against default pg_hba.conf with trust as authentication method, it will fail. Hence these failures. Please use tesh.sh to test the extension or change the pg_hba.conf accordingly before running the tests.
